### ISSUE TITLE
Generar archivo AP con códigos de diagnostico postqúirurgicos.

### ISSUE THREAD

**Issue by gestiontics** [tics-clinica-colombia/SIIS_TEST#12]
# Generar archivo AP con códigos de diagnostico postqúirurgicos.

El sistema debe generar el archivo `AP` con los códigos de diagnostico postqirúrgicos diferentes al T888.

**Comment by davidcgarcia** [comment]
Se reviso, El archivo AP, eliminando el código T888; sin embargo en algunas filas el código se encuentra como NULL en la base de datos, por lo cual puede ser posible que el paciente no tenga asignado código de diagnostico postquirúrgicos en el archivo AP
