### ISSUE TITLE
Evitar generar líneas vacías en los archivos.

### ISSUE THREAD

**Issue by gestiontics** [tics-clinica-colombia/SIIS_TEST#24]
# Evitar generar líneas vacías en los archivos.

El sistema no debe permitir en ningún archivo generar líneas vacías. (Actualmente ocurre en el archivo `AP`)

**Comment by davidcgarcia** [comment]
Se eliminar líneas en blanco en el archivo AP y en el archivo CT, ya que el usuario manifiesta que sólo en esos dos archivos se generan líneas en blanco.
